M48
; DRILL file {KiCad (6.0.7)} date Fri Jul 29 08:46:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-29T08:46:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X0.6387Y-0.4229
X0.6387Y-0.5411
T2
X1.2717Y-0.2885
X1.3717Y-0.29
T0
M30
